<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'eba',
	'db_user' => 'eba',
	'db_password' => '123EBA321',
	'db_server_version' => '5.5.5-10.0.29-MariaDB-0ubuntu0.16.04.1',
	'mailer_from_name' => 'Ines Garcia Lanza',
	'mailer_from_email' => 'eba@cookingmedia.com.ar',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '24bda7a1a3457111a2e6e8f6aab17715d697bdd10860efc6cac5e9c817a1db42',
	'site_url' => 'http://63.141.233.213/mautic/index.php',
	'webroot' => null,
	'cache_path' => '/var/www/html/mautic/app/cache',
	'log_path' => '/var/www/html/mautic/app/logs',
	'image_path' => 'media/images',
	'tmp_path' => '/var/www/html/mautic/app/cache',
	'theme' => 'Mauve',
	'locale' => 'es',
	'dev_hosts' => "63.141.233.213",
	'trusted_hosts' => array(

	),
	'trusted_proxies' => array(

	),
	'rememberme_key' => '25767556495ab7933ad71ed95fd3b2dcc30e29ce',
	'rememberme_lifetime' => '31536000',
	'rememberme_path' => '/',
	'rememberme_domain' => null,
	'default_pagelimit' => 30,
	'default_timezone' => 'UTC',
	'date_format_full' => 'F j, Y g:i a T',
	'date_format_short' => 'D, M d',
	'date_format_dateonly' => 'F j, Y',
	'date_format_timeonly' => 'g:i a',
	'ip_lookup_service' => 'maxmind_download',
	'ip_lookup_auth' => null,
	'ip_lookup_config' => array(

	),
	'update_stability' => 'stable',
	'cookie_path' => '/',
	'cookie_domain' => null,
	'cookie_secure' => null,
	'cookie_httponly' => 0,
	'do_not_track_ips' => array(

	),
	'do_not_track_internal_ips' => array(

	),
	'link_shortener_url' => null,
	'cached_data_timeout' => '10',
	'batch_sleep_time' => 1,
	'batch_campaign_sleep_time' => false,
	'cors_restrict_domains' => 1,
	'cors_valid_domains' => array(

	),
	'rss_notification_url' => 'https://mautic.com/?feed=rss2&tag=notification',
	'api_enabled' => 0,
	'api_enable_basic_auth' => false,
	'api_oauth2_access_token_lifetime' => 60,
	'api_oauth2_refresh_token_lifetime' => 14,
	'api_batch_max_limit' => 200,
	'upload_dir' => '/var/www/html/mautic/app/../media/files',
	'max_size' => '6',
	'allowed_extensions' => array(
		"0" => "csv",
		"1" => "doc",
		"2" => "docx",
		"3" => "epub",
		"4" => "gif",
		"5" => "jpg",
		"6" => "jpeg",
		"7" => "mpg",
		"8" => "mpeg",
		"9" => "mp3",
		"10" => "odt",
		"11" => "odp",
		"12" => "ods",
		"13" => "pdf",
		"14" => "png",
		"15" => "ppt",
		"16" => "pptx",
		"17" => "tif",
		"18" => "tiff",
		"19" => "txt",
		"20" => "xls",
		"21" => "xlsx",
		"22" => "wav"
	),
	'campaign_time_wait_on_event_false' => 'PT1H',
	'mailer_return_path' => null,
	'mailer_append_tracking_pixel' => 1,
	'mailer_convert_embed_images' => 0,
	'mailer_amazon_region' => 'email-smtp.us-east-1.amazonaws.com',
	'mailer_spool_msg_limit' => null,
	'mailer_spool_time_limit' => null,
	'mailer_spool_recover_timeout' => '900',
	'mailer_spool_clear_timeout' => '1800',
	'unsubscribe_text' => '<a href=\'|URL|\'>Unsubscribe</a> to no longer receive emails from us.',
	'webview_text' => '<a href=\'|URL|\'>Having trouble reading this email? Click here.</a>',
	'unsubscribe_message' => 'We are sorry to see you go! |EMAIL| will no longer receive emails from us. If this was by mistake, <a href=\'|URL|\'>click here to re-subscribe</a>.',
	'resubscribe_message' => '|EMAIL| has been re-subscribed. If this was by mistake, <a href=\'|URL|\'>click here to unsubscribe</a>.',
	'monitored_email' => array(
		"general" => array(
			"address" => "",
			"host" => "",
			"port" => "993",
			"encryption" => "/ssl",
			"user" => "",
			"password" => ""
		),
		"EmailBundle_bounces" => array(
			"address" => "",
			"host" => "",
			"port" => "993",
			"encryption" => "/ssl",
			"user" => "",
			"password" => "",
			"override_settings" => "",
			"folder" => "",
			"ssl" => "1"
		),
		"EmailBundle_unsubscribes" => array(
			"address" => "",
			"host" => "",
			"port" => "993",
			"encryption" => "/ssl",
			"user" => "",
			"password" => "",
			"override_settings" => "",
			"folder" => "",
			"ssl" => "1"
		)
	),
	'mailer_is_owner' => 0,
	'default_signature_text' => 'Best regards, |FROM_NAME|',
	'email_frequency_number' => null,
	'email_frequency_time' => null,
	'show_contact_preferences' => 0,
	'show_contact_frequency' => 0,
	'show_contact_pause_dates' => 0,
	'show_contact_preferred_channels' => 0,
	'show_contact_categories' => 0,
	'show_contact_segments' => 0,
	'mailer_mailjet_sandbox' => 0,
	'mailer_mailjet_sandbox_default_mail' => null,
	'notification_enabled' => 0,
	'notification_landing_page_enabled' => 1,
	'notification_app_id' => null,
	'notification_rest_api_key' => null,
	'notification_safari_web_id' => null,
	'gcm_sender_id' => '482941778795',
	'welcomenotification_enabled' => 1,
	'cat_in_page_url' => 0,
	'google_analytics' => null,
	'track_contact_by_ip' => 0,
	'redirect_list_types' => array(
		"301" => "mautic.page.form.redirecttype.permanent",
		"302" => "mautic.page.form.redirecttype.temporary"
	),
	'sms_enabled' => 0,
	'sms_username' => null,
	'sms_password' => null,
	'sms_sending_phone_number' => null,
	'sms_frequency_number' => null,
	'sms_frequency_time' => null,
	'saml_idp_own_password' => null,
	'saml_idp_email_attribute' => 'EmailAddress',
	'saml_idp_username_attribute' => null,
	'saml_idp_firstname_attribute' => 'FirstName',
	'saml_idp_lastname_attribute' => 'LastName',
	'saml_idp_default_role' => 1,
	'webhook_start' => 0,
	'webhook_limit' => 1000,
	'webhook_log_max' => 10,
	'queue_mode' => 'immediate_process',
	'twitter_handle_field' => 'twitter',
);
